### ISSUE TITLE
Please add support for uploading precompiled .hex

### ISSUE THREAD

**Issue by AndKe** [Renaud11232/OctoPrint-Marlin-Flasher#3]
It is actually more work to:  (having installed Arduino CLI)
-zip the sketch directory, 
-upload it

than:
(I am very much likely to have Marlin sketch already open for editing)
-hit Ctrl-R (build it, on much more powerful computer)
-upload /tmp/arduino/marlin.ino.hex

**Comment by Renaud11232** [comment]
Hello, thanks for the idea.

I will give it a try in the near future. I didn't think about it

**Comment by Renaud11232** [comment]
Hello again,

I had some spear time today so it now supports .zip and .hex sketches :)

**Comment by AndKe** [comment]
Fantastic ! , thank you.
