### ISSUE TITLE
please update documentation with "which arduino-cli."

### ISSUE THREAD

**Issue by AndKe** [Renaud11232/OctoPrint-Marlin-Flasher#31]
till now, it has been "arduino-cli-latest-linuxarm.tar.bz2"
now there are LinuxARM v6 , v7, and 64 
It would be great to know which one is for RPi / (OctoPi)  - probably the most used hardware.

**Comment by Renaud11232** [comment]
Hello, I'll add that to the Wiki

**Comment by Renaud11232** [comment]
I've added a line on the [Arduino Installation page](https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/wiki/Arduino-Installation) telling to use ARMv6 for Raspberry Pi's.
