### ISSUE TITLE
octoprint stuck on Marlin Flash 

### ISSUE THREAD

**Issue by id0-labs** [Renaud11232/OctoPrint-Marlin-Flasher#32]
Hi, I have my octoprint main page stuck on Marlin Flasher wizard page, the note on it says that I should be able to continue by clicking finish but I have tried nothing I still on the wizard page thus can't use octoprint at the moment.

How I can disable or uninstall Marlin Flash maybe through command line so I can at least access my octoprint? I have attached a picture so you can see where I'm stuck. Any help will be appreciated.

<img width="1145" alt="Screen Shot 2019-11-30 at 3 33 19 PM" src="https://user-images.githubusercontent.com/20234814/69906304-1742fc00-1387-11ea-9baa-43cdd2cc958c.png">

**Comment by Renaud11232** [comment]
Hello,
I have a few questions : 

Which version did you install ?
If you don't know, do you know when/how you installed it ?

Which browser are you using ?

And what system are you running it on ? (Windows, Linux, Raspberry...) ?

Thanks

**Comment by id0-labs** [comment]
So I have installed it a while ago, and I do know I'm not running the latest version of Marlin Flasher because I have OctoPod app on my phone as that is the only way I can use octoprint right now and it does tell me that there is a new version of Marlin Flasher.

I'm using Safari as my main browser but I did try on chrome and firefox, I'm still unable to go pass the wizard page

And I'm running octoprint on a Raspberry Pi

**Comment by Renaud11232** [comment]
Thanks,

You can uninstall it using commandline :
```bash
~/oprint/bin/pip uninstall OctoPrint-Marlin-Flasher
```
This will probably need Octoprint to be restarted.

But just before you do that, can check a few things, so I can know why it does that.
Can you check in your browser console if you have any error when you press the finish/next button
On Chrome, press F12 and go to the console tab.

It might also be useful if you could send your octoprint logs.

Thank you and I hope it helps

**Comment by id0-labs** [comment]
yes of course I can do that. Can you tell me how to get the octoprint logs? so I can get that and send it over

So here is what I'm seeing on the console side
<img width="551" alt="Screen Shot 2019-11-30 at 4 18 25 PM" src="https://user-images.githubusercontent.com/20234814/69906703-1ad98180-138d-11ea-9191-c95a2bc723ce.png">

**Comment by Renaud11232** [comment]
Thank you,

The logs can be found in `~/.octoprint/logs`
There should be one named `octoprint.log`.

Also, it seems there's one error occuring before the screenshot you gave. Is it the same one repeating or is it a different one ?

**Comment by id0-labs** [comment]
Yes it was the same error I just try it multiple times to make sure I wasn't seeing any other error.

Here is the log

<img width="1278" alt="Screen Shot 2019-11-30 at 4 31 25 PM" src="https://user-images.githubusercontent.com/20234814/69906806-e36bd480-138e-11ea-9273-6aaf25a3b7b6.png">

**Comment by id0-labs** [comment]
I'm unable to use the command line you sent me to uninstall Marlin Flasher. I was able to get to the bin folder, I do see PIP in the list but trying to get to it I get an error saying pip: not a directory. Am I missing something?

**Comment by Renaud11232** [comment]
Did you type 
```
~/oprint/bin/pip uninstall OctoPrint-Marlin-Flasher
```
or
```
cd ~/oprint/bin/pip uninstall OctoPrint-Marlin-Flasher
```
Indeed, pip is not a directory it's an executable.

If you are in the `~/oprint/bin/` folder you can type
```
./pip uninstall OctoPrint-Marlin-Flasher
```
But the first command should work as is, no matter the folder you currently are in.

I hope I'm clear :/

**Comment by id0-labs** [comment]
Ah got it thanks, I was trying to cd into the folder first. I was able to get it.

Thank you again for your help with this

**Comment by Renaud11232** [comment]
No problem,

I'll close this.

But the error you got does not come from my plugin. but indeed can prevent the UI to work and thus the wizard page. I really don't know where it comes from.
