### ISSUE TITLE
pyduinocli version mismatch

### ISSUE THREAD

**Issue by Renaud11232** [Renaud11232/OctoPrint-Marlin-Flasher#34]
This is recreated from #30 
I suspect 0.3.0 does not support the newest pyduinocli.

**Comment by FrancYescO** [comment]
```
Name: pyduinocli
Version: 0.4.1
Summary: Wrapper library around arduino-cli
Home-page: https://github.com/Renaud11232/pyduinocli
Author: Renaud Gaspard
Author-email: gaspardrenaud@hotmail.com
License: UNKNOWN
Location: /home/pi/oprint/lib/python2.7/site-packages
Requires:
Required-by: OctoPrint-Marlin-Flasher
```

**Comment by Renaud11232** [comment]
If it's what i think it is, this should now be fixed.
Can you check if 0.3.1 fixed it ?

**Comment by FrancYescO** [comment]
should be in prod? the check updates says all up to date
nvm, force check update found the new ver

**Comment by FrancYescO** [comment]
ehm, MarlinFlasher totally disappeared from my octoprint

**Comment by Renaud11232** [comment]
Well, well, well.
Can you restart OctoPrint/reload the page, and resend the logs ?

**Comment by FrancYescO** [comment]
after another reboot after the one after MarlinFlasher upgrade, it come back and board selection and search is working :)

**Comment by Renaud11232** [comment]
Oh so it does work. Nice
I'll close this then.

Thanks for your patience
