### ISSUE TITLE
Add support for arduino-cli 0.7.x

### ISSUE THREAD

**Issue by Renaud11232** [Renaud11232/OctoPrint-Marlin-Flasher#35]
A new version for arduino-cli is out.

**Comment by mark-hahn** [comment]
does 0.7.2 work?

**Comment by Renaud11232** [comment]
Hello, I totally forgot about this.
The code was already written I just forgot to create a release for it. Thanks for reminding me
So now, yes, it should work. (You will have to update to the latest release of the plugin `0.3.2`).
Octoprint might not see the new release imediately.
