### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by mikekscholz** [Renaud11232/OctoPrint-Marlin-Flasher#4]
Just for the sake of clarification, is this the same as the firmware updater but without the added step of compiling a hex file in arduino ide first?

**Comment by Renaud11232** [comment]
That was the base idea, yeah. Being able to send the zipped firmware code directly into Octoprint and let the plugin do the compilation and upload.

But there's a bit more than just that :
* This plugin now also support precompiled .hex files
* This plugin works (theoratically) with all Arduino boards and bootloader that Arduino IDE supports.

I hope it helped
