### ISSUE TITLE
/dev/ttyACM0/firmware.bin: Not a directory - Failed.

### ISSUE THREAD

**Issue by GithStreamer** [Renaud11232/OctoPrint-Marlin-Flasher#40]
I have followed the instructions and installed the Marlin Flasher as well as the platformio components.  When I drop the zip file into the Marlin Flasher in Octoprint, it takes a moment to compile.  It says Uploading and gets about half way through the progress bar and then says - /dev/ttyACM0/firmware.bin: Not a directory - Failed.  I have tried looking around but am drawing a blank.

**Comment by Renaud11232** [comment]
This might be a bug as `/dev/ttyACM0/firmware.bin` is indeed not a directory, and in fact should not exist at all.
I recently got an SKR 1.3 too but didn't had the time to replace my current board.
Once I mount it on my printer, I'll be able to try to look into this.

**Comment by Renaud11232** [comment]
Hello,
In order to get it working you have to install an additional piece of software.
The [wiki](https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/wiki/PlatformIO-Installation) should help to know how to get it working.
