### ISSUE TITLE
[FR] PlatformIO: Get -e parameter from pins.h

### ISSUE THREAD

**Issue by thinkyhead** [Renaud11232/OctoPrint-Marlin-Flasher#41]
There is a way for the plugin to automatically select the correct environment for a PlatformIO build and not require users to edit their `platformio.ini` file and change the default environment.

If you read the `MOTHERBOARD` value in `Marlin/Configuration.h` and then search for the corresponding `MB(...)` line in `pins/pins.h`, the end of the following `#include` line contains one or more `env:` designations. When there's only one, that can be stuck into the `-e` parameter. When there's more than one then the plugin can display a selector.

The basis of this has already been implemented as part of the `auto_build.py` script that comes with Marlin. I'm in the process of porting over the behavior handled by that Python script directly into the "Auto Build Marlin" extension for VSCode, so then there will be a working Javascript implementation and UI possibly more transportable to an OctoPrint plugin.

**Comment by Renaud11232** [comment]
Oh neat.
I didn't know `pins.h` contained such information.
