### ISSUE TITLE
Display the date/time of the uploaded sketch when flashing

### ISSUE THREAD

**Issue by ForsakenNGS** [Renaud11232/OctoPrint-Marlin-Flasher#43]
It would be quite nice to simply see the timestamp of when the sketch was uploaded before flashing, just for being able to double-check the upload worked. Especially when repeatedly flashing firmare I had situations where I was not sure if I did already (successfully) upload the new sketch and had no way to validate that.

**Comment by Renaud11232** [comment]
Just a little update on this.
I've added a field that shows if the firmware was uploaded and when : 
This will be released in 0.3.4.
![image](https://user-images.githubusercontent.com/13933802/75286092-274c6980-5818-11ea-88b9-0bc8947ab37b.png)


![image](https://user-images.githubusercontent.com/13933802/75286129-38957600-5818-11ea-97a7-4a1252577f54.png)
