### ISSUE TITLE
PlatformIO install instructions

### ISSUE THREAD

**Issue by heatvent** [Renaud11232/OctoPrint-Marlin-Flasher#45]
I am not a linux user but should we us "which" instead of "where" in linux?  

Current Instructions:
> Once it is installed, you will need to know where it got installed. To do this you can do (Linux and Windows' cmd) :
> 
> where platformio

Proposed:
```
Once it is installed, you will need to know where it got installed. To do this you can do (Linux) :

which platformio
```

**Comment by Renaud11232** [comment]
You are totally right, I updated the wiki
