### ISSUE TITLE
cannot execute upload tool: fork/exec avrdude: no such file or directory

### ISSUE THREAD

**Issue by cron410** [Renaud11232/OctoPrint-Marlin-Flasher#46]
Running Octoprint on x86 CPU. Here's the full error.
`Error during Upload: cannot execute upload tool: fork/exec /root/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/bin/avrdude: no such file or directory`

I have verified `avrdude` is present and executable. I also replaced that executable with one I installed manually from the OS repo, that did not work either. Same error `no such file or directory`
```
~/.octoprint # ls -la /root/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/bin/avrdude
-rwxr-xr-x    1 root     root        537192 Mar  1 23:01 /root/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/bin/avrdude
~/.octoprint # ls
arduino-cli      config.yaml      logs             scripts          supervisord.log  translations     watched
avrdude          data             plugins          slicingProfiles  supervisord.pid  uploads
config.backup    generated        printerProfiles  socat.sh         timelapse        virtualSd
~/.octoprint # rm /root/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/bin/avrdude
~/.octoprint # mv avrdude /root/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/bin/
```

**Comment by Renaud11232** [comment]
Hello,

Which version of arduino-cli are you using (version number/32 vs 64 bits) ?
Which distro are you using (32/64)?
Which cores/libraries were installed ?
What board options did you use ?

I'll see if I manage to reproduce this.

Also, you should not have to interfer with the avrdude version used by arduino-cli
