### ISSUE TITLE
The flask dependency is not working with OP 1.4.0

### ISSUE THREAD

**Issue by pegr69** [Renaud11232/OctoPrint-Marlin-Flasher#47]
OP has changed to flask v 0.12.5 and this plugin downgrades flask to 0.10, causing op to fail dependencies during startup.

**Comment by Renaud11232** [comment]
Hello,

The issus should be fixed in [0.3.4rc2](https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/releases/tag/0.3.4rc2).

I still need to fully test it before releasing 0.3.4.
