### ISSUE TITLE
Is Bigtreeetech SKR 1.x supported?

### ISSUE THREAD

**Issue by AndKe** [Renaud11232/OctoPrint-Marlin-Flasher#54]
I am about to switch to SKR 1.4 , if I compile the .bin file, can OctoPrint+Marlin-Flasher upload it to SKR 1.3 ?

**Comment by Renaud11232** [comment]
Hello,

SKR boards are supported (I use one myself) but require some extra steps.
To be able to upload the firmware you'll need to install platformio.
The wiki should tell how to install platformio and how to set everything up for `ARMmbed` boards (like the skr 1.3)

[PlatformIO installation](https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/wiki/PlatformIO-Installation)
[PlatformIO installation#armmbed-boards](https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/wiki/PlatformIO-Installation#armmbed-boards)
[PlatformIO flashing](https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/wiki/PlatformIO-Flashing)

I hope it helped
