### ISSUE TITLE
IMG file

### ISSUE THREAD

**Issue by tj51** [Renaud11232/OctoPrint-Marlin-Flasher#58]
can you please add a option to load a img file to the printer to your program, thank you, Tj

**Comment by Renaud11232** [comment]
I'm cleaning up issues.

If you are using `arduino-cli`, you should already be able to upload .hex files.

If you are using `PlatformIO`, there is no way of directly using a bin file the same way arduino-cli does. I don't believe PlatformIO provides a way to do this

However, I will look if adding #71 is possible which will probably help solve this issue.
