### ISSUE TITLE
Clarification of the firmware compilation process

### ISSUE THREAD

**Issue by narfel** [Renaud11232/OctoPrint-Marlin-Flasher#60]
Very new to this, so sorry if this is obvious. The scope of this plugin is to compile and upload on the octoprint host via cli? Is there a way to upload and flash just a bin that was compiled on a different machine?

**Comment by narfel** [comment]
I think this answer by @AvanOsch is quite the same than what i ask for. 

 @AvanOsch in https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/issues/56#issuecomment-720703295_

**Comment by Renaud11232** [comment]
Hello,

Sorry for the late answer.

Currently, using Arduino-cli you can upload and flash either a zip file containing the source code or a compiled `.hex` file.

Using platform.io, you can only use the source code.

I hope this helps
