### ISSUE TITLE
Minor UX improvements

### ISSUE THREAD

**Issue by FrancYescO** [Renaud11232/OctoPrint-Marlin-Flasher#61]
Just to speedup a flashing procedure (upload file and click flash) i suggest to move the flash button/progressbar in the first accordion with the browse button, and the all other options to another "Settings" accordion, due to the fact that basically are things that you are not going to look often.

Another nice option to have is autoreconnect after successfull or failed (or better don't disconnect if a zip fails to compile) flashing process

**Comment by Renaud11232** [comment]
In version 0.5.0, the printer should reconnect even if the flashing process failed.

Regarding the placement of the upload and flash sections, I think the way it's currently layed out is clearer. It does take a few more clicks to get the job done if all libraries and cores are already installed. But it does follow the standard steps of the flashing process in order, which might be clearer for people who aren't very confortable with the process of flashing their board.
