### ISSUE TITLE
The configured path does not point to an arduino-cli executable.

### ISSUE THREAD

**Issue by kd7eir** [Renaud11232/OctoPrint-Marlin-Flasher#62]
The configured path DOES point to the arduino-cli executable, it's version 0.10.0, I can call it from a command prompt and use it. Is there some magic incantation needed to make this plugin actually see the file?

**Comment by Renaud11232** [comment]
Hello,

Sorry for the late answer.

Is the file executable by the user running octoprint ?

**Comment by Bajotaz** [comment]
Got the same problem as kd7eir

**Comment by CrystalJP** [comment]
I am also having this issue, I can run it from cmd as any user and I think my path is correct.

**Comment by CrystalJP** [comment]
"C:\Users\John-Paul\Desktop\OctoPrint\arduino-cli_0.9.0_Windows_64bit\arduino-cli.exe"

does this look correct?

**Comment by Renaud11232** [comment]
It does look correct.

Can you provide the logs from OctoPrint as well as the output from the follwing command so I can try to see what's going on :

```
C:\Users\John-Paul\Desktop\OctoPrint\arduino-cli_0.9.0_Windows_64bit\arduino-cli.exe version --format json
```

Thanks
