### ISSUE TITLE
Add a way to use a path instead of uploading a zip/hex

### ISSUE THREAD

**Issue by Renaud11232** [Renaud11232/OctoPrint-Marlin-Flasher#7]
> Is it possible to just have it uncompressed in a directory so people can just text edit whatever files they may need to?

Recreated from #5

**Comment by tobias-theobald** [comment]
Another use case would be that people could provide their "Marlin fork" (i.e. their configured Marlin in their own Git repo) and the plugin could `git pull` it before installing it.

**Comment by Renaud11232** [comment]
Sorry, but due to recent changes in arduino-cli, I must fix some compatibility problems first, and I won't probably have the time for this after, I'm closing the issue
