### ISSUE TITLE
Confusing about WindowsPath under Linux in Settings example

### ISSUE THREAD

**Issue by Fiiti** [Renaud11232/OctoPrint-Marlin-Flasher#72]
Hi together,

I am confused about the using.
In your examples you have entered a WindowsPath to platform-io  - but Octoprint is running on an raspi/linux.

In the reality I would like to upload to the printer from octoprint only the hex file.

For what did i must enter an arduino cli oder platform-io path?

So I am very confused abot the generel using.

Thank your for your assistance in advanced.

Fi

**Comment by Renaud11232** [comment]
Hello,

OctoPrint can run on pretty much any OS, not only a Raspbian. I took those screenshots on the machine I use when developping the plugin which is a Windows computer. But it will work on linux as well with linux paths like.`/path/where/you/installed/platformio`.

In the current state of the plugin, there is no way to upload a precompiled hex file using Platform-io. I'm looking into adding a way to solve that in the future.

However, if your board can be flashed using Arduino, you can flash a `hex` file using `arduino-cli` instead.

I hope that helped
