### ISSUE TITLE
The configured path does not point to PlatformIO-Core

### ISSUE THREAD

**Issue by bluespider42** [Renaud11232/OctoPrint-Marlin-Flasher#74]
On OctoPi I have platformio installed, as per the instructions, in a virtualenv. `which pio` gives `/usr/bin/pio` however the plugin reports `The configured path does not point to PlatformIO-Core`. I can run `pio` from the command line (after activating the venv).

**Comment by Renaud11232** [comment]
Hello,

If PlatformIO is installed in a virtualenv, it should not be in `/usr/bin/pio`. Usually, it's installed in `<path_to_virtualenv>/bin/pio` where <path_to_virtualenv> is the path to your virtualenv.

If that doesn't work. can you send the output of the following commands :

To check it is indeed installed in /usr/bin : 
```bash
ls -la /usr/bin/pio
/usr/bin/pio --version
```

To check if pio was correctly installed in the venv : 
```bash
ls <path_to_virtualenv>/bin
```

Thanks
