### ISSUE TITLE
fail to install Arduino 

### ISSUE THREAD

**Issue by broncosis** [Renaud11232/OctoPrint-Marlin-Flasher#84]
**Describe the bug**

the Arduino install fails on RPI-3 

Unable to detect architecture : armv6l

**To Reproduce**

1. load clean image of octopi
2. install this plugin 
3. and reboot 
4. then atempt to install arduino 

**Expected behavior**

it should install the ardunio-cli

**Screenshots**

Marlin flasher 1.01

[octoprint.log](https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/files/8347432/octoprint.log)

using Firefox

**Comment by broncosis** [comment]
[octoprint(1).log](https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/files/8347442/octoprint.1.log)
 updated log with debugging turned on 

also I have just recently installed the very same version on the same PI image  checked the version number 
same version and it works fine 

but I was able to try a PI zero w I had around and this failed the same way 
I will compare versions of updates installed shortly

**Comment by Renaud11232** [comment]
Hello,

Thanks for reporting this.
Starting from v1.0.2 (just published now), you should be able to install arduino-cli for `armv6l` as well.

**Comment by broncosis** [comment]
works great thanks
