### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by heatvent** [Renaud11232/OctoPrint-Marlin-Flasher#9]
It would be great to get feedback on what is going on when flashing (compiling, flashing, reading, writing, etc.).  Not sure if this is possible.

**Comment by Renaud11232** [comment]
Hello,
It is partially possible. By partially I mean flashing with arduino-cli is a two step process: compile then upload. And with the current version of arduino-cli there is no way to get detailed progress on each step.
Anyway I can look into adding something like a progress bar going from 0>50>100% for the compile and upload steps.
