### ISSUE TITLE
Error: Please specify `upload_port` for environment or use global `--upload-port` option.

### ISSUE THREAD

**Issue by agp009** [Renaud11232/OctoPrint-Marlin-Flasher#96]
**Describe the bug**

Trying to flash updated marlin file onto SKR1.4 Turbo board. Currently running on Windows. Get following message and unsure how to resolve: 

Unable to find destination disk ([Errno 2] No such file or directory: '/media/pi')
Please select it in platformio.ini using the upload_port keyword (https://docs.platformio.org/en/latest/projectconf/section_env_upload.html) or copy the firmware (.pio/build/LPC1769/firmware.bin) manually to the appropriate disk

**To Reproduce**

1. Upload platformio.ini zip file to Marlin Flasher (works without issue)
2. Set Board type to LPC1769 (works without issue)
3. Click Flash
4. File eventually compiles after long time
5. File fails to upload with above error message

**Expected behavior**

Expectation was for updated Marlin file to flash onto 3D printer for continued printing use.

**Screenshots**

![image](https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/assets/37482307/b3dd2ee9-0e0e-4bc8-ac22-0ecdc070f02e)

**Version of OctoPrint-Marlin-Flasher**

Marlin Flasher 1.0.7

**Server configuration**
 - OS: Windows
 - Browser Microsoft Edge

**OctoPrint logs with `octoprint.plugins.marlin_flasher` set to DEBUG**

**Comment by Renaud11232** [comment]
Hello,

Looking at the screenshot it looks like OctoPrint is running on a Raspberry Pi (which is Linux based) and not Windows.
There are additional steps required to upload firmware on mbed boards from linux.
These steps are detailed [here in the wiki](https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/wiki/PlatformIO-Installation#armmbed-boards).

Can you follow them and try again ?
